### ISSUE TITLE
Reference Pages - Javascript not being called

### ISSUE THREAD

**Issue by joeyklee** [ml5js/ml5-website-archive#36]
Currently the javascript is not being called in the examples for the reference pages. 

<img width="1452" alt="Screen Shot 2019-05-10 at 18 41 53" src="https://user-images.githubusercontent.com/3622055/57560229-6413a680-7353-11e9-8615-15263361b0cd.png">
<img width="1552" alt="Screen Shot 2019-05-10 at 18 41 43" src="https://user-images.githubusercontent.com/3622055/57560230-6544d380-7353-11e9-8dbc-41f945f7c1c7.png">

**Comment by wenqili** [comment]
Yes, it won't work, right now I'm using `dangerouslysetInnerHTML` to parse examples, it’s the same as `innerHTML`, which won't execute `<script>`, `eval()` won't work too since there is no jquery loaded.

Please use `react halmet` to load scripts for now, I'll solve it soon.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wenqili** [comment]
@joeyklee I just update the example tabpanel.

To add examples in a model page:
At docs/reference/the-name-of-model.md, in front matter, add

```
# support multi examples

examples: 

 - title: {string} title of example 1
   github: {string} url to github
   demo: {string} url to iframe page
   code: {string, will automaticall parse to code block} code snippet 

 - title: {string} title of example 2
   github: {string} url to github
   demo: {string} url to iframe page
   code: {string, will automaticall parse to code block} code snippet 
```

[Here is a live example](https://ml5-website-2.netlify.com/reference/api-Pix2Pix/)
